// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLjMpAaGvWY9kQa_SKw3HF6f8RqNCXjMQ',
    appId: '1:878629315964:web:661c492dac9e92e3e2f0f9',
    messagingSenderId: '878629315964',
    projectId: 'chat-app-82ced',
    authDomain: 'chat-app-82ced.firebaseapp.com',
    storageBucket: 'chat-app-82ced.appspot.com',
    measurementId: 'G-PCRT4E52ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySGBSmRggTtXBd7f8-9ftZVOaMVK1axw',
    appId: '1:878629315964:android:7219ce9b22c470cfe2f0f9',
    messagingSenderId: '878629315964',
    projectId: 'chat-app-82ced',
    storageBucket: 'chat-app-82ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxJ6YetyqmEA7Qftya6D_tHqZcu8Fppzo',
    appId: '1:878629315964:ios:e90f1a31d544c5cbe2f0f9',
    messagingSenderId: '878629315964',
    projectId: 'chat-app-82ced',
    storageBucket: 'chat-app-82ced.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxJ6YetyqmEA7Qftya6D_tHqZcu8Fppzo',
    appId: '1:878629315964:ios:e5107831ddd2f286e2f0f9',
    messagingSenderId: '878629315964',
    projectId: 'chat-app-82ced',
    storageBucket: 'chat-app-82ced.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
